[project]
name = "python-for-devops"
version = "0.1.0"
description = "Python For DevOps â€“ course tasks and examples"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "psutil>=5.9.0",
    "requests>=2.28.0",
    "boto3>=1.26.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.22.0",
]
